[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 200
[profile.forking]
url = "https://eth-mainnet.g.alchemy.com/v2/nsXvKew2RkxJEbcXLlWa3DcbaUAncLhC"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
